name: Copy Docker Image
on: 
  workflow_dispatch:
    inputs:
      source:
        description: '镜像源 (Registry)'     
        required: true
        default: 'docker.io'
      destination:
        description: '目标源 (Registry)'
        required: true
        default: 'registry.cn-shenzhen.aliyuncs.com'
      source_repo:
        description: '仓库及标签 (格式 repo:tag)'
        required: true
        default: ''
      destination_repo:
        description: '目标仓库及标签 (格式 repo:tag)'
        required: true
        default: ''

